global using Hahn.Customers.Domain.Abstractions;
global using Hahn.Customers.Domain.Aggregates;
global using Hahn.Customers.Domain.Events;
global using Hahn.Customers.Domain.Exceptions;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
